name: marketplace-action
on:
  push:
    branches: 
      - 'work/actions-practice'
jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
            python-version: '3.13' 
      - name: Print statement in Python
        run: |
          echo "Hello Python"
          python --version
  
          
          
        
      
